docs: update web3 roadmap, open source projects, eth dev tooling
FrancescoXX/free-Web3-resources pull request #172
Opened 2022-10-06 10:50 UTC by therealharpaljadeja

## 👨‍💻 Changes proposed

- [x] Mentioning the speaker in the web3 roadmap video
- [x] Added celo-composer to open source projects
- [x] Added celo-composer to eth dev tooling
- [x]  Added Celo Developer Blog under blogs
- [x] Removed Duplicate Blogs and Web3 Roadmap section.

2022-10-06 14:54 UTC, Atharv181 approved these changes
Looks good to me

2022-10-09 05:56 UTC, FrancescoXX requested changes

2022-10-09 05:56 UTC, FrancescoXX commented on README.md
> -
please put this back

2022-10-09 05:56 UTC, FrancescoXX commented on README.md
> -## Blogs
please put this back

2022-10-09 05:56 UTC, FrancescoXX commented on README.md
> -## Web3 Roadmaps (Hindi/ Urdu)
please put this back

2022-10-30 17:15 UTC, merged