adding web3 journey by eda and swarm in file storage sec
FrancescoXX/free-Web3-resources pull request #38
Opened 2022-04-19 05:43 UTC by tawseefnabi

## 🛠️ Fixes Issue

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2022-04-22 16:23 UTC, krshdev reviewed
Hi, Thanks for the contribution, I think the description for the storage one, .ight just be too long, but I'm not sure since that is just my opinion, I'd like to hear more on this from the maintainers

2022-04-22 16:38 UTC, FrancescoXX commented on README.md
> +- [My web3 journey in 100 days](https://eda.hashnode.dev/my-web3-journey-day-100-of-100daysofweb3) by [Eda](https://twitter.com/edatweets_)
please move this to the Ethereum free resources

2022-07-22 15:48 UTC, FrancescoXX requested changes

2022-07-22 15:48 UTC, FrancescoXX commented on README.md
> +- [My web3 journey in 100 days](https://eda.hashnode.dev/my-web3-journey-day-100-of-100daysofweb3) by [Eda](https://twitter.com/edatweets_)
Please take a look here @tawseefnabi

2022-08-26 15:36 UTC, merged