Update README.md
FrancescoXX/free-Web3-resources pull request #52
Opened 2022-05-09 20:42 UTC by ajl388

## 🛠️ Fixes Issue

## 👨‍💻 Changes proposed

Added more tutorials and fixed typo.

## ✔️ Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2022-05-10 10:33 UTC, Pradumnasaraf requested changes

2022-05-10 10:33 UTC, Pradumnasaraf commented on README.md
> +- [Buildspace](https://buildspace.com/) Onboarding devs to web3. Start building cool stuff right now, earn NFTs, access secret opportunities in crypto.
```suggestion
- [Buildspace](https://buildspace.so/) Onboarding devs to web3. Start building cool stuff right now, earn NFTs, access secret opportunities in crypto.
```

Hey `https://buildspace.so` is correct one, please chnage back to it 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-05-10 11:10 UTC, ewainy requested changes
Great addition for Cadena 😊
As @Pradumnasaraf has pointed out, please amend buildspace link to buildspace.so

2022-05-13 16:11 UTC, FrancescoXX commented
For now, I don't see the community (like a discord or Slack channel)

Please revert the Buildspace link

2022-05-13 18:00 UTC, ajl388 reviewed
Updated links.
Discord community: https://discord.gg/UQayXxzazc

2022-07-22 15:58 UTC, merged